version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
